// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vplvvsbacfckqnsyquen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwbHZ2c2JhY2Zja3Fuc3lxdWVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMjM0NjksImV4cCI6MjA1OTY5OTQ2OX0.sUB39tfiooREevk0LJFREhRBe5-xs9XRK2XgoaNSXlk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);