// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahfpwecgaidipkdatlut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoZnB3ZWNnYWlkaXBrZGF0bHV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzOTA2MDgsImV4cCI6MjA1OTk2NjYwOH0.B3L-2bi3-evZl1b_6GvIfal2jaVvlFaNkvrlIpMPhyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);